SELECT 
PERS.PERS_ID, 
PERS.PERS_NR, 
PERS.PERS_VNAME, 
PERS.PERS_NAME, 
PERS.PERS_GEBDAT, 
PERS.PERS_STR, 
PERS.PERS_ORT, 
PERS.PERS_PLZ,
PERS.PERS_EMAIL,
PERS.PERS_EMAIL2,
PERS_DYN.ALPHA6
FROM PERS, PERS_DYN WHERE PERS_DYN.PERS_ID = PERS.PERS_ID AND PERS_NR = '6942069'; -- <--KUNDENNUMMER