SELECT PERS_ANKURZ AS Anrede, 
PERS_GESCHL AS Geschlecht, 
PERS_NAME AS Name, 
PERS_VNAME AS Vorname, 
PERS_TITEL AS Titel, 
PERS_STR AS Strasse, 
PERS_PLZ AS PLZ, 
PERS_ORT AS Ort, 
PERS_EMAIL AS Email, 
VER_BEGINN AS Datum, 
FTZ AS Fahrtechnikzentrum, 
DATENWEITERGABE AS Einverstaendnis, 
GG_BEZ AS KFZModell FROM V_TXT_FZG_TN_EXPORT 
WHERE FIRMA_ID= 'xxxx' 
AND VER_JAHR= 'xxxx'
AND VER_MONAT= 'xxxx' 
ORDER BY DATENWEITERGABE ASC;