SELECT VTYP.VTYP_ID, 
VTYP.VTYP_BEZ, 
ZZ_VTYP_VERS.VERS_SCHUTZ,
ZZ_VTYP_DYN.VERS_POL_LFZG,
ZZ_VTYP_DYN.VERS_POL_TNFZG,
ZZ_VTYP_DYN.VERS_VERRECH,
ZZ_VTYP_DYN.VTYP_VERS_TEXT_K

FROM ZZ_VTYP_VERS, VTYP, ZZ_VTYP_DYN   
WHERE VTYP.VTYP_ID = ZZ_VTYP_VERS.VTYP_ID 
AND VTYP.VTYP_ID = ZZ_VTYP_DYN.VTYP_ID
AND (VTYP.VTYP_BEZ like 'NPD%'
or VTYP.VTYP_BEZ like 'PEC%'
or VTYP.VTYP_BEZ like 'PHY%'
or VTYP.VTYP_BEZ like 'RST%'
or VTYP.VTYP_BEZ like 'SAM%'
or VTYP.VTYP_BEZ like 'SCH%'
or VTYP.VTYP_BEZ like 'NBI%'
or VTYP.VTYP_BEZ like 'AGM%'
or VTYP.VTYP_BEZ like 'KAR%'
or VTYP.VTYP_BEZ like 'ECS%'
or VTYP.VTYP_BEZ like 'MTT%'
or VTYP.VTYP_BEZ like 'EGE%'
or VTYP.VTYP_BEZ like 'EGM%'
or VTYP.VTYP_BEZ like 'EGO%'
or VTYP.VTYP_BEZ like 'EFT%'
or VTYP.VTYP_BEZ like 'EXT%'
or VTYP.VTYP_BEZ like 'INC%'
or VTYP.VTYP_BEZ like 'NFK%'
or VTYP.VTYP_BEZ like 'NFL%'
or VTYP.VTYP_BEZ like 'NIC%'
or VTYP.VTYP_BEZ like 'NLX%'
or VTYP.VTYP_BEZ like 'QEB%'
or VTYP.VTYP_BEZ like 'QEL%'
or VTYP.VTYP_BEZ like 'QFL%'
or VTYP.VTYP_BEZ like 'QGB%'
or VTYP.VTYP_BEZ like 'QGL%'
or VTYP.VTYP_BEZ like 'QLB%'
or VTYP.VTYP_BEZ like 'QLL%'
or VTYP.VTYP_BEZ like 'QLT%'
or VTYP.VTYP_BEZ like 'QRB%'
or VTYP.VTYP_BEZ like 'QRL%'
or VTYP.VTYP_BEZ like 'QW1%'
or VTYP.VTYP_BEZ like 'QW2%'
or VTYP.VTYP_BEZ like 'QW3%'
or VTYP.VTYP_BEZ like 'QW4%'
or VTYP.VTYP_BEZ like 'QW5%'
or VTYP.VTYP_BEZ like 'QW6%'
or VTYP.VTYP_BEZ like 'QZB%'
or VTYP.VTYP_BEZ like 'VOK%'
or VTYP.VTYP_BEZ like 'SMT%'
or VTYP.VTYP_BEZ like 'PRE%'
or VTYP.VTYP_BEZ like 'PMO%'
or VTYP.VTYP_BEZ like 'NAT%');